# Copyright (C) 2024 Blackview BV9900Pro Device Tree
# Licensed under the Apache License, Version 2.0

# Device Information
TARGET_BOARD_PLATFORM := mt6779
TARGET_BOOTLOADER_BOARD_NAME := bv9900pro
TARGET_BOARD_INFO_FILE := device/blackview/bv9900pro/board-info.txt

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a53

# CPU
TARGET_CPU_SMP := true
TARGET_CPU_CORTEX_A55 := true
TARGET_CPU_CORTEX_A75 := true

# Memory
TARGET_USES_64_BIT_BINDER := true
TARGET_USES_HWC2 := true

# Storage
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4

# Partition sizes (in bytes)
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 3758096384
BOARD_VENDORIMAGE_PARTITION_SIZE := 922746880
BOARD_USERDATAIMAGE_PARTITION_SIZE := 32212254720
BOARD_CACHEIMAGE_PARTITION_SIZE := 452984832

# File system
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_USERDATAIMAGE_PARTITION_SIZE := 32212254720

# Recovery
TARGET_RECOVERY_FSTAB := device/blackview/bv9900pro/recovery.fstab
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_RECOVERY_SWIPE := true
BOARD_SUPPRESS_EMMC_WIPE := true
BOARD_SUPPRESS_SECURE_ERASE := true

# Graphics
TARGET_USES_HWC2 := true
TARGET_USES_GRALLOC1 := true
TARGET_USES_GRALLOC4 := true
TARGET_USES_HWC2ON1ADAPTER := true
TARGET_USES_ION := true

# Display
TARGET_SCREEN_DENSITY := 480
TARGET_SCREEN_HEIGHT := 2280
TARGET_SCREEN_WIDTH := 1080

# Camera
TARGET_CAMERA_NEEDS_ZSL := true
TARGET_CAMERA_USE_EXTENDED_FORMAT := true
TARGET_CAMERA_APP_VERSION_CODE := 1

# Audio
BOARD_USES_ALSA_AUDIO := true
BOARD_SUPPORTS_SOUND_TRIGGER := true
USE_CUSTOM_AUDIO_POLICY := 1

# WiFi
BOARD_WLAN_DEVICE := MediaTek
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_mt66xx
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_mt66xx
WIFI_DRIVER_FW_PATH_PARAM := "/dev/wmtWifi"
WIFI_DRIVER_FW_PATH_STA := STA
WIFI_DRIVER_FW_PATH_AP := AP
WIFI_DRIVER_FW_PATH_P2P := P2P

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_MTK := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/blackview/bv9900pro/bluetooth

# GPS
BOARD_GPS_LIBRARIES := true
BOARD_MEDIATEK_USES_GPS := true

# Sensors
BOARD_SENSOR_ST := true
BOARD_SENSOR_MPU := true
BOARD_SENSOR_AKM := true

# USB
TARGET_USES_MEDIATEK_USB := true
TARGET_USES_MEDIATEK_USB_FUNCS := true

# Charger
BOARD_CHARGER_ENABLE_SUSPEND := true
BOARD_CHARGER_DISABLE_INIT_BLANK := true
BOARD_CHARGER_SHOW_PERCENTAGE := true

# Security
BOARD_SECCOMP_POLICY := device/blackview/bv9900pro/seccomp_policy

# SELinux
BOARD_SEPOLICY_DIRS := \
    device/blackview/bv9900pro/sepolicy

# Kernel
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_KERNEL_CROSS_COMPILE_PREFIX := aarch64-linux-android-
TARGET_KERNEL_SOURCE := kernel/blackview/bv9900pro
TARGET_KERNEL_CONFIG := bv9900pro_defconfig

# Device Tree
BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_KERNEL_TAGS_OFFSET := 0x07808000
BOARD_KERNEL_SECOND_OFFSET := 0x00e88000
BOARD_RAMDISK_OFFSET := 0x07c08000
BOARD_DTB_OFFSET := 0x07808000
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2
BOARD_MKBOOTIMG_ARGS := --base 0x40078000 --pagesize 2048 --kernel_offset 0x00008000 --ramdisk_offset 0x07c08000 --second_offset 0x00e88000 --tags_offset 0x07808000 --dtb_offset 0x07808000

# Build
TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := false
TARGET_NO_RECOVERY := false
TARGET_NO_RADIOIMAGE := true

# Vendor
BOARD_VNDK_VERSION := current
BOARD_VNDK_RUNTIME_DISABLE := true

# Properties
TARGET_SYSTEM_PROP := device/blackview/bv9900pro/system.prop
TARGET_VENDOR_PROP := device/blackview/bv9900pro/vendor.prop

# Treble
PRODUCT_FULL_TREBLE := true
PRODUCT_TREBLE_LINKER_NAMESPACES := true
PRODUCT_SHIPPING_API_LEVEL := 28

# A/B
AB_OTA_UPDATER := false

# OTA
TARGET_OTA_ASSERT_DEVICE := bv9900pro,BV9900Pro

# Inherit from common
-include device/mediatek/mt6779/BoardConfig.mk

